name: WLED compile

on:
    workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Run PlatformIO
      run: |
        rm -rf /tmp/WLEDtemp/* || true
        mkdir -p /tmp/WLEDtemp
        wget https://github.com/moonmodules/WLED/archive/refs/heads/mdev.zip -O /tmp/WLEDtemp/mm.zip
        unzip /tmp/WLEDtemp/mm.zip -d /tmp/WLEDtemp
        find /tmp/WLEDtemp -maxdepth 1 -mindepth 1 -name "*" -type d >> /tmp/WLEDtemp/wledfoldername
        cd `cat /tmp/WLEDtemp/wledfoldername`
        echo '[env:custom_build]' >>platformio.ini
        echo 'extends = env:esp32dev' >>platformio.ini
        echo 'build_flags = ${env:esp32dev.build_flags} ${common.debug_flags} -D SR_DEBUG -D MIC_LOGGER -D LEDPIN=21 -D DEFAULT_LED_COUNT=144 -D ABL_MILLIAMPS_DEFAULT=0 -D USERMOD_DALLASTEMPERATURE -D USERMOD_DHT -D USERMOD_DHT_CELSIUS -D USERMOD_AUTO_SAVE -D USERMOD_FOUR_LINE_DISPLAY -D USERMOD_PING_PONG_CLOCK -D USERMOD_WORDCLOCK -D USERMOD_ANALOG_CLOCK -D USERMOD_ROTARY_ENCODER_UI -D USERMOD_MODE_SORT -D USERMOD_ANIMATED_STAIRCASE -D USERMOD_MULTI_RELAY -D USERMOD_BATTERY -D USERMOD_SENSORSTOMQTT -D USERMOD_PIRSWITCH -D USERMOD_BME280 -D USERMOD_RTC -D RGB_ROTARY_ENCODER -D USERMOD_PWM_FAN -D USERMOD_DALLASTEMPERATURE -D USERMOD_PWM_OUTPUTS -D USERMOD_ADS1115 -D USERMOD_SEVEN_SEGMENT -D USERMOD_SSDR -D USERMOD_SN_PHOTORESISTOR' >>platformio.ini
        echo 'lib_deps = ' >>platformio.ini
        echo '  ${env:esp32dev.lib_deps}' >>platformio.ini
        echo '  OneWire@~2.3.5' >>platformio.ini
        echo '  https://github.com/alwynallan/DHT_nonblocking' >>platformio.ini
        echo '  olikraus/U8g2 @ ^2.28.8' >>platformio.ini
        echo '  olikraus/U8g2 @ ^2.28.8' >>platformio.ini
        echo '  Wire' >>platformio.ini
        echo '  adafruit/Adafruit BMP280 Library @ 2.1.0' >>platformio.ini
        echo '  adafruit/Adafruit CCS811 Library @ 1.0.4' >>platformio.ini
        echo '  adafruit/Adafruit Si7021 Library @ 1.4.0' >>platformio.ini
        echo '  adafruit/Adafruit Unified Sensor' >>platformio.ini
        echo '  BME280@~3.0.0' >>platformio.ini
        echo '  Wire' >>platformio.ini
        echo '  lennarthennigs/ESP Rotary@^1.5.0' >>platformio.ini
        echo '  adafruit/Adafruit BusIO @ 1.13.2' >>platformio.ini
        echo '  adafruit/Adafruit ADS1X15 @ 2.4.0' >>platformio.ini
        echo '  adafruit/Adafruit Unified Sensor' >>platformio.ini
        
        pio run -e custom_build || pio run -e custom_build
    - name: Copy Files
      run: |
        cd $GITHUB_WORKSPACE
        git rm -r $GITHUB_WORKSPACE/*.bin || true
        WLEDFOLDERNAME=`cat /tmp/WLEDtemp/wledfoldername`
        cp ${WLEDFOLDERNAME}/build_output/firmware/custom_build.bin $GITHUB_WORKSPACE/
        date -I | tr -d '\n' >$GITHUB_WORKSPACE/last_update_date.txt
    - name: Commit Files
      run: |
        cd $GITHUB_WORKSPACE
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git add $GITHUB_WORKSPACE/custom_build.bin
        git add $GITHUB_WORKSPACE/last_update_date.txt
        git commit -m "Commit Custom Build"
        git push origin main
